# Generated by Django 3.2.8 on 2021-10-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viralload',
            old_name='distrit',
            new_name='district',
        ),
        migrations.AlterField(
            model_name='viralload',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
