# Generated by Django 3.2.8 on 2021-11-01 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='person_id',
        ),
    ]
