# Generated by Django 3.2.8 on 2021-10-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211028_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='observation',
            name='synced',
            field=models.BooleanField(default=False),
        ),
    ]
