# Generated by Django 3.2.8 on 2021-10-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211028_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viralload',
            name='laboratory_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
