# Generated by Django 3.2.8 on 2021-10-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_viralload_viral_load'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viralload',
            name='viral_load',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
