# Generated by Django 3.2.8 on 2021-10-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_viralload_formatted_nid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratory_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sector', models.CharField(blank=True, max_length=30, null=True)),
                ('number_orig_lab', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('health_facility', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('capture_date', models.DateField(blank=True, null=True)),
                ('access_date', models.DateField(blank=True, null=True)),
                ('nid', models.CharField(blank=True, max_length=100, null=True)),
                ('viral_load', models.CharField(blank=True, max_length=100, null=True)),
                ('viral_load_qualitative', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
